In [2]:
import csv
import pandas as pd

In [3]:
# read the csv file
# make pd out of all the csv files in this director

df = pd.read_csv('/Users/alt2005/ai_advisor/AI-Advisor/columbia_courses_invalid.csv')
df.head()

,course_code,course_title,department,section,times,location,instructor,credits,enrollment,description,url
0,NaN,AFAS UN1003 Blackness and Frenchness: A Radica...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,https://bulletin.columbia.edu/columbia-college...
1,NaN,AFAS UN3030 AFRICAN-AMERICAN MUSIC. 3.00 points.,NaN,NaN,NaN,NaN,NaN,3.0,NaN,This course focuses on a central question: how...,https://bulletin.columbia.edu/columbia-college...
2,NaN,AFAS UN3936 Black Intellectuals Seminar. 4 poi...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,https://bulletin.columbia.edu/columbia-college...
3,NaN,AFAS GU4031 POPULAR MUSIC/PROTEST MOVEMNTS. 4....,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,https://bulletin.columbia.edu/columbia-college...
4,NaN,AFAS GU4035 Criminal Justice and the Carceral ...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,https://bulletin.columbia.edu/columbia-college...

In [5]:
df_2 = pd.read_csv('/Users/alt2005/ai_advisor/AI-Advisor/columbia_courses.csv')
df_2.head(20)

,course_code,course_title,department,section,times,location,instructor,credits,enrollment,description,url
0,AFAS 1001,INTRO TO AFRICAN-AMER STUDIES.,AFAS,001/11355,M W 2:40pm - 3:55pm,Room TBA,Nyle Fort,4.00,100/100,Prerequisites: Students need to register for a...,https://bulletin.columbia.edu/columbia-college...
1,AFAS 1002,Major Debates in African-American Studies.,AFAS,001/11353,W 12:10pm - 2:00pm,758 Ext Schermerhorn Hall,Jafari Allen,4.00,12/12,Prerequisites: Students must register for disc...,https://bulletin.columbia.edu/columbia-college...
2,AFAS 3943,Senior Pro Seminar.,AFAS,001/13522,W 12:10pm - 2:00pm,Room TBA,Farah Griffin,4.00,8/12,This course is a seminar for seniors to either...,https://bulletin.columbia.edu/columbia-college...
3,AFAS 3930,TOPICS IN THE BLACK EXPERIENCE.,AFAS,002/18240,T 4:10pm - 6:00pm,758 Ext Schermerhorn Hall,Johanna Almiron,4.00,7/12,Please refer to African American and African D...,https://bulletin.columbia.edu/columbia-college...
4,AFAS 3940,SENIOR THESIS SEMINAR.,AFAS,001/10703,Th 4:10pm - 6:00pm,758 Ext Schermerhorn Hall,Megan French-Marcelin,4.00,2/12,The Senior Seminar will afford thesis writers ...,https://bulletin.columbia.edu/columbia-college...
5,AFAS 4080,Black Feminist Imaginaries: Practices and Poet...,AFAS,002/10694,W 2:10pm - 4:00pm,758 Ext Schermerhorn Hall,Jafari Allen,4.00,8/15,"This seminar will focus on theories, practices...",https://bulletin.columbia.edu/columbia-college...
6,AFAS 4080,Black Feminist Imaginaries: Practices and Poet...,AFAS,003/10697,W 12:10pm - 2:00pm,311 Fayerweather,Vivaldi Jean-Marie,4.00,7/15,"This seminar will focus on theories, practices...",https://bulletin.columbia.edu/columbia-college...
7,AFAS 4080,Black Feminist Imaginaries: Practices and Poet...,AFAS,004/15618,Th 2:10pm - 4:00pm,505 Lewisohn Hall,Anthony Johnson,4.00,4/12,"This seminar will focus on theories, practices...",https://bulletin.columbia.edu/columbia-college...
8,AFAS 4080,Black Feminist Imaginaries: Practices and Poet...,AFAS,005/15626,M 2:10pm - 4:00pm,401 Hamilton Hall,Nyle Fort,4.00,17/19,"This seminar will focus on theories, practices...",https://bulletin.columbia.edu/columbia-college...
9,AFAS 4080,Black Feminist Imaginaries: Practices and Poet...,AFAS,006/17396,W 2:10pm - 4:00pm,313 Pupin Laboratories,Obery Hendricks,4.00,3/12,"This seminar will focus on theories, practices...",https://bulletin.columbia.edu/columbia-college...
10,AFAS 4080,Black Feminist Imaginaries: Practices and Poet...,AFAS,008/17398,M 12:10pm - 2:00pm,212d Lewisohn Hall,Veronique Charles,4.00,3/15,"This seminar will focus on theories, practices...",https://bulletin.columbia.edu/columbia-college...
11,AFAS 4080,Black Feminist Imaginaries: Practices and Poet...,AFAS,009/18923,T 4:10pm - 6:00pm,507 Lewisohn Hall,Samiya Bashir,4.00,7/12,"This seminar will focus on theories, practices...",https://bulletin.columbia.edu/columbia-college...
12,AFAS 4080,Black Feminist Imaginaries: Practices and Poet...,AFAS,001/11903,T 12:10pm - 2:00pm,Room TBA,Rachel Grace Newman,4.00,6/12,"This seminar will focus on theories, practices...",https://bulletin.columbia.edu/columbia-college...
13,AFAS 4080,Black Feminist Imaginaries: Practices and Poet...,AFAS,002/11356,T 12:10pm - 2:00pm,758 Ext Schermerhorn Hall,Jafari Allen,4.00,9/12,"This seminar will focus on theories, practices...",https://bulletin.columbia.edu/columbia-college...
14,AFAS 4080,Black Feminist Imaginaries: Practices and Poet...,AFAS,003/15607,M 12:10pm - 2:00pm,758 Ext Schermerhorn Hall,Veronique Charles,4.00,2/12,"This seminar will focus on theories, practices...",https://bulletin.columbia.edu/columbia-college...
15,AFAS 3001,SING A BLACK GIRL'S SONG: THE NON FICTION WRIT...,AFAS,001/10689,Th 2:10pm - 4:00pm,608 Lewisohn Hall,Edwidge Danticat,4.00,9/15,This undergraduate seminar offers an in-depth ...,https://bulletin.columbia.edu/columbia-college...
16,AMST 3930,Topics in American Studies. 4 points.,AMST,001/12262,T 2:10pm - 4:00pm,Room TBA,Hilary-Anne Hallett,4,9/18,NaN,https://bulletin.columbia.edu/columbia-college...
17,AMST 3930,Topics in American Studies. 4 points.,AMST,002/12273,W 12:10pm - 2:00pm,Room TBA,John McWhorter,4,0/18,NaN,https://bulletin.columbia.edu/columbia-college...
18,AMST 3930,Topics in American Studies. 4 points.,AMST,003/12341,T 10:10am - 12:00pm,Room TBA,James Stephen Shapiro,4,13/18,NaN,https://bulletin.columbia.edu/columbia-college...
19,AMST 3930,Topics in American Studies. 4 points.,AMST,004/12342,M 6:10pm - 8:00pm,Room TBA,Benjamin Rosenberg,4,0/18,NaN,https://bulletin.columbia.edu/columbia-college...