In [1]:
import csv
import pandas as pd

In [ ]:
# read the csv file
# make pd out of all the csv files in this director

df = pd.read_csv('test_results_invalid_20250710_210506.csv')
df.head()

,course_code,course_title,department,section,times,location,instructor,credits,enrollment,description,url
0,NaN,COMS E3899 Research Training. 0.00 points.,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Research training course. Recommended in prepa...,https://bulletin.columbia.edu/columbia-college...
1,NaN,COMS E3999 Fieldwork. 1 point.,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,https://bulletin.columbia.edu/columbia-college...
2,NaN,COMS E4115 PROGRAMMING LANG ＆ TRANSL. 3.00 poi...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,https://bulletin.columbia.edu/columbia-college...
3,NaN,COMS E4773 Machine Learning Theory. 3.00 points.,NaN,NaN,NaN,NaN,NaN,3.0,NaN,Theoretical study of algorithms for machine le...,https://bulletin.columbia.edu/columbia-college...
4,NaN,COMS E4775 Causal Inference. 3 points.,NaN,NaN,NaN,NaN,NaN,3.0,NaN,Prerequisites: (COMS4711W) and,https://bulletin.columbia.edu/columbia-college...

In [3]:
df_2 = pd.read_csv('test_results_valid_20250710_210506.csv')
df_2.head()

,course_code,course_title,department,section,times,location,instructor,credits,enrollment,description,url
0,COMS W3998,UNDERGRAD PROJECTS IN COMPUTER SCIENCE. 1.00-,COMS,NaN,NaN,NaN,NaN,3.0,NaN,NaN,https://bulletin.columbia.edu/columbia-college...
1,COMS W3998,UNDERGRAD PROJECTS IN COMPUTER SCIENCE. 1.00-,COMS,NaN,NaN,NaN,NaN,3.0,NaN,NaN,https://bulletin.columbia.edu/columbia-college...
2,COMS 1001,Introduction to Information Science. 3 points.,COMS,001/12789,T Th 10:10am - 11:25am,Room TBA,Adam Cannon,3.0,45/60,NaN,https://bulletin.columbia.edu/columbia-college...
3,COMS 1002,COMPUTING IN CONTEXT.,COMS,001/12790,T Th 1:10pm - 2:25pm,Room TBA,"Adam Cannon, Mark Santolucito",4.0,97/300,Introduction to elementary computing concepts ...,https://bulletin.columbia.edu/columbia-college...
4,COMS 1002,COMPUTING IN CONTEXT.,COMS,002/12791,T Th 1:10pm - 2:25pm,Room TBA,Mark Santolucito,4.0,19/60,Introduction to elementary computing concepts ...,https://bulletin.columbia.edu/columbia-college...